# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enviarnoticia.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'enviarnoticia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65nviarnoticia.proto\x12\renviarnoticia\"b\n\rClientRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\x05\x12\r\n\x05passw\x18\x02 \x01(\t\x12\x0e\n\x06titulo\x18\x03 \x01(\t\x12\x11\n\tcontenido\x18\x04 \x01(\t\x12\x0f\n\x07seccion\x18\x05 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2T\n\rEnviarNoticia\x12\x43\n\x08SendNews\x12\x1c.enviarnoticia.ClientRequest\x1a\x17.enviarnoticia.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enviarnoticia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=38
  _globals['_CLIENTREQUEST']._serialized_end=136
  _globals['_RESPONSE']._serialized_start=138
  _globals['_RESPONSE']._serialized_end=166
  _globals['_ENVIARNOTICIA']._serialized_start=168
  _globals['_ENVIARNOTICIA']._serialized_end=252
# @@protoc_insertion_point(module_scope)
