# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import suscripciones_noticias_pb2 as suscripciones__noticias__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in suscripciones_noticias_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuscripcionesNoticiasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribirCliente = channel.unary_unary(
                '/suscripciones.SuscripcionesNoticias/SubscribirCliente',
                request_serializer=suscripciones__noticias__pb2.ClienteArea.SerializeToString,
                response_deserializer=suscripciones__noticias__pb2.Respuesta.FromString,
                _registered_method=True)
        self.BorrarSuscripcion = channel.unary_unary(
                '/suscripciones.SuscripcionesNoticias/BorrarSuscripcion',
                request_serializer=suscripciones__noticias__pb2.ClienteArea.SerializeToString,
                response_deserializer=suscripciones__noticias__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerNoticiasDeArea = channel.unary_unary(
                '/suscripciones.SuscripcionesNoticias/ObtenerNoticiasDeArea',
                request_serializer=suscripciones__noticias__pb2.ClienteArea.SerializeToString,
                response_deserializer=suscripciones__noticias__pb2.ListaNoticias.FromString,
                _registered_method=True)


class SuscripcionesNoticiasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribirCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrarSuscripcion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerNoticiasDeArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuscripcionesNoticiasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribirCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribirCliente,
                    request_deserializer=suscripciones__noticias__pb2.ClienteArea.FromString,
                    response_serializer=suscripciones__noticias__pb2.Respuesta.SerializeToString,
            ),
            'BorrarSuscripcion': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrarSuscripcion,
                    request_deserializer=suscripciones__noticias__pb2.ClienteArea.FromString,
                    response_serializer=suscripciones__noticias__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerNoticiasDeArea': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerNoticiasDeArea,
                    request_deserializer=suscripciones__noticias__pb2.ClienteArea.FromString,
                    response_serializer=suscripciones__noticias__pb2.ListaNoticias.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suscripciones.SuscripcionesNoticias', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('suscripciones.SuscripcionesNoticias', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuscripcionesNoticias(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribirCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suscripciones.SuscripcionesNoticias/SubscribirCliente',
            suscripciones__noticias__pb2.ClienteArea.SerializeToString,
            suscripciones__noticias__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrarSuscripcion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suscripciones.SuscripcionesNoticias/BorrarSuscripcion',
            suscripciones__noticias__pb2.ClienteArea.SerializeToString,
            suscripciones__noticias__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerNoticiasDeArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/suscripciones.SuscripcionesNoticias/ObtenerNoticiasDeArea',
            suscripciones__noticias__pb2.ClienteArea.SerializeToString,
            suscripciones__noticias__pb2.ListaNoticias.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
