# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import areas_pb2 as areas__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in areas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminAreasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddArea = channel.unary_unary(
                '/adminareas.AdminAreas/AddArea',
                request_serializer=areas__pb2.ClientRequest.SerializeToString,
                response_deserializer=areas__pb2.Response.FromString,
                _registered_method=True)
        self.DeleteArea = channel.unary_unary(
                '/adminareas.AdminAreas/DeleteArea',
                request_serializer=areas__pb2.ClientRequest.SerializeToString,
                response_deserializer=areas__pb2.Response.FromString,
                _registered_method=True)
        self.ShowAreas = channel.unary_unary(
                '/adminareas.AdminAreas/ShowAreas',
                request_serializer=areas__pb2.AreasRequest.SerializeToString,
                response_deserializer=areas__pb2.Response.FromString,
                _registered_method=True)


class AdminAreasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAreas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminAreasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddArea': grpc.unary_unary_rpc_method_handler(
                    servicer.AddArea,
                    request_deserializer=areas__pb2.ClientRequest.FromString,
                    response_serializer=areas__pb2.Response.SerializeToString,
            ),
            'DeleteArea': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArea,
                    request_deserializer=areas__pb2.ClientRequest.FromString,
                    response_serializer=areas__pb2.Response.SerializeToString,
            ),
            'ShowAreas': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAreas,
                    request_deserializer=areas__pb2.AreasRequest.FromString,
                    response_serializer=areas__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adminareas.AdminAreas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adminareas.AdminAreas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminAreas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adminareas.AdminAreas/AddArea',
            areas__pb2.ClientRequest.SerializeToString,
            areas__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adminareas.AdminAreas/DeleteArea',
            areas__pb2.ClientRequest.SerializeToString,
            areas__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowAreas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adminareas.AdminAreas/ShowAreas',
            areas__pb2.AreasRequest.SerializeToString,
            areas__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
