# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agente_pb2 as agente__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agente_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Servicio_AgenteStub(object):
    """Servicio
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerNoticiasUltimas24hs = channel.unary_unary(
                '/agente.Servicio_Agente/ObtenerNoticiasUltimas24hs',
                request_serializer=agente__pb2.noticiasRequest.SerializeToString,
                response_deserializer=agente__pb2.noticiasInfo.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/agente.Servicio_Agente/Login',
                request_serializer=agente__pb2.LoginDatos.SerializeToString,
                response_deserializer=agente__pb2.ResultadoLogin.FromString,
                _registered_method=True)
        self.AgregarCategoria = channel.unary_unary(
                '/agente.Servicio_Agente/AgregarCategoria',
                request_serializer=agente__pb2.DatosAgregarCategoria.SerializeToString,
                response_deserializer=agente__pb2.ResultadoAgregarCategoria.FromString,
                _registered_method=True)
        self.SuscribirNuevaCategoria = channel.unary_unary(
                '/agente.Servicio_Agente/SuscribirNuevaCategoria',
                request_serializer=agente__pb2.DatosSuscribirNuevaCategoria.SerializeToString,
                response_deserializer=agente__pb2.ResultadoSuscribirNuevaCategoria.FromString,
                _registered_method=True)
        self.BorrarArea = channel.unary_unary(
                '/agente.Servicio_Agente/BorrarArea',
                request_serializer=agente__pb2.DatosBorrarArea.SerializeToString,
                response_deserializer=agente__pb2.RespuestaBorrarArea.FromString,
                _registered_method=True)
        self.EnviarNoticia = channel.unary_unary(
                '/agente.Servicio_Agente/EnviarNoticia',
                request_serializer=agente__pb2.DatosEnviarNoticia.SerializeToString,
                response_deserializer=agente__pb2.RespuestaEnviarNoticia.FromString,
                _registered_method=True)
        self.BorrarSuscripcionCategoria = channel.unary_unary(
                '/agente.Servicio_Agente/BorrarSuscripcionCategoria',
                request_serializer=agente__pb2.DatosSuscribirNuevaCategoria.SerializeToString,
                response_deserializer=agente__pb2.ResultadoSuscribirNuevaCategoria.FromString,
                _registered_method=True)
        self.ObtenerUltimasNoticias = channel.unary_unary(
                '/agente.Servicio_Agente/ObtenerUltimasNoticias',
                request_serializer=agente__pb2.DatosObtenerUltimasNoticias.SerializeToString,
                response_deserializer=agente__pb2.noticiasInfo.FromString,
                _registered_method=True)
        self.VerCategoriasInscripto = channel.unary_unary(
                '/agente.Servicio_Agente/VerCategoriasInscripto',
                request_serializer=agente__pb2.DatosVerCategoriasInscripto.SerializeToString,
                response_deserializer=agente__pb2.RespuestaCategoriaInscripto.FromString,
                _registered_method=True)


class Servicio_AgenteServicer(object):
    """Servicio
    """

    def ObtenerNoticiasUltimas24hs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuscribirNuevaCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrarArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarNoticia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrarSuscripcionCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerUltimasNoticias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerCategoriasInscripto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Servicio_AgenteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerNoticiasUltimas24hs': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerNoticiasUltimas24hs,
                    request_deserializer=agente__pb2.noticiasRequest.FromString,
                    response_serializer=agente__pb2.noticiasInfo.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=agente__pb2.LoginDatos.FromString,
                    response_serializer=agente__pb2.ResultadoLogin.SerializeToString,
            ),
            'AgregarCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarCategoria,
                    request_deserializer=agente__pb2.DatosAgregarCategoria.FromString,
                    response_serializer=agente__pb2.ResultadoAgregarCategoria.SerializeToString,
            ),
            'SuscribirNuevaCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.SuscribirNuevaCategoria,
                    request_deserializer=agente__pb2.DatosSuscribirNuevaCategoria.FromString,
                    response_serializer=agente__pb2.ResultadoSuscribirNuevaCategoria.SerializeToString,
            ),
            'BorrarArea': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrarArea,
                    request_deserializer=agente__pb2.DatosBorrarArea.FromString,
                    response_serializer=agente__pb2.RespuestaBorrarArea.SerializeToString,
            ),
            'EnviarNoticia': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarNoticia,
                    request_deserializer=agente__pb2.DatosEnviarNoticia.FromString,
                    response_serializer=agente__pb2.RespuestaEnviarNoticia.SerializeToString,
            ),
            'BorrarSuscripcionCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrarSuscripcionCategoria,
                    request_deserializer=agente__pb2.DatosSuscribirNuevaCategoria.FromString,
                    response_serializer=agente__pb2.ResultadoSuscribirNuevaCategoria.SerializeToString,
            ),
            'ObtenerUltimasNoticias': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerUltimasNoticias,
                    request_deserializer=agente__pb2.DatosObtenerUltimasNoticias.FromString,
                    response_serializer=agente__pb2.noticiasInfo.SerializeToString,
            ),
            'VerCategoriasInscripto': grpc.unary_unary_rpc_method_handler(
                    servicer.VerCategoriasInscripto,
                    request_deserializer=agente__pb2.DatosVerCategoriasInscripto.FromString,
                    response_serializer=agente__pb2.RespuestaCategoriaInscripto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agente.Servicio_Agente', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agente.Servicio_Agente', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Servicio_Agente(object):
    """Servicio
    """

    @staticmethod
    def ObtenerNoticiasUltimas24hs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/ObtenerNoticiasUltimas24hs',
            agente__pb2.noticiasRequest.SerializeToString,
            agente__pb2.noticiasInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/Login',
            agente__pb2.LoginDatos.SerializeToString,
            agente__pb2.ResultadoLogin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/AgregarCategoria',
            agente__pb2.DatosAgregarCategoria.SerializeToString,
            agente__pb2.ResultadoAgregarCategoria.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuscribirNuevaCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/SuscribirNuevaCategoria',
            agente__pb2.DatosSuscribirNuevaCategoria.SerializeToString,
            agente__pb2.ResultadoSuscribirNuevaCategoria.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrarArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/BorrarArea',
            agente__pb2.DatosBorrarArea.SerializeToString,
            agente__pb2.RespuestaBorrarArea.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarNoticia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/EnviarNoticia',
            agente__pb2.DatosEnviarNoticia.SerializeToString,
            agente__pb2.RespuestaEnviarNoticia.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrarSuscripcionCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/BorrarSuscripcionCategoria',
            agente__pb2.DatosSuscribirNuevaCategoria.SerializeToString,
            agente__pb2.ResultadoSuscribirNuevaCategoria.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerUltimasNoticias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/ObtenerUltimasNoticias',
            agente__pb2.DatosObtenerUltimasNoticias.SerializeToString,
            agente__pb2.noticiasInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerCategoriasInscripto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agente.Servicio_Agente/VerCategoriasInscripto',
            agente__pb2.DatosVerCategoriasInscripto.SerializeToString,
            agente__pb2.RespuestaCategoriaInscripto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
