# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: areas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'areas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61reas.proto\x12\nadminareas\"<\n\rClientRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\x05\x12\r\n\x05passw\x18\x02 \x01(\t\x12\x0c\n\x04\x61rea\x18\x03 \x01(\t\"-\n\x0c\x41reasRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\x05\x12\r\n\x05passw\x18\x02 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2\xca\x01\n\nAdminAreas\x12<\n\x07\x41\x64\x64\x41rea\x12\x19.adminareas.ClientRequest\x1a\x14.adminareas.Response\"\x00\x12?\n\nDeleteArea\x12\x19.adminareas.ClientRequest\x1a\x14.adminareas.Response\"\x00\x12=\n\tShowAreas\x12\x18.adminareas.AreasRequest\x1a\x14.adminareas.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'areas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=27
  _globals['_CLIENTREQUEST']._serialized_end=87
  _globals['_AREASREQUEST']._serialized_start=89
  _globals['_AREASREQUEST']._serialized_end=134
  _globals['_RESPONSE']._serialized_start=136
  _globals['_RESPONSE']._serialized_end=164
  _globals['_ADMINAREAS']._serialized_start=167
  _globals['_ADMINAREAS']._serialized_end=369
# @@protoc_insertion_point(module_scope)
