# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tareas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tareas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctareas.proto\x12\x06tareas\"1\n\x0cLoginRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\x05\x12\x10\n\x08password\x18\x02 \x01(\t\";\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11mensaje_a_mostrar\x18\x02 \x01(\t\"!\n\x0eGetNewsRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\x05\"B\n\x0fGetNewsResponse\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\t\x12\x0c\n\x04hora\x18\x03 \x01(\t\"\'\n\x14\x44\x65leteNewNewsRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\x05\"C\n\x15\x44\x65leteNewNewsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11mensaje_a_mostrar\x18\x02 \x01(\t2\xcf\x01\n\rTareasService\x12\x34\n\x05Login\x12\x14.tareas.LoginRequest\x1a\x15.tareas.LoginResponse\x12:\n\x07GetNews\x12\x16.tareas.GetNewsRequest\x1a\x17.tareas.GetNewsResponse\x12L\n\rDeleteNewNews\x12\x1c.tareas.DeleteNewNewsRequest\x1a\x1d.tareas.DeleteNewNewsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tareas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=24
  _globals['_LOGINREQUEST']._serialized_end=73
  _globals['_LOGINRESPONSE']._serialized_start=75
  _globals['_LOGINRESPONSE']._serialized_end=134
  _globals['_GETNEWSREQUEST']._serialized_start=136
  _globals['_GETNEWSREQUEST']._serialized_end=169
  _globals['_GETNEWSRESPONSE']._serialized_start=171
  _globals['_GETNEWSRESPONSE']._serialized_end=237
  _globals['_DELETENEWNEWSREQUEST']._serialized_start=239
  _globals['_DELETENEWNEWSREQUEST']._serialized_end=278
  _globals['_DELETENEWNEWSRESPONSE']._serialized_start=280
  _globals['_DELETENEWNEWSRESPONSE']._serialized_end=347
  _globals['_TAREASSERVICE']._serialized_start=350
  _globals['_TAREASSERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
